// The one normaliser for everything cloud-bound — the JavaScript twin of
// src/taskmining/normalise.py (design of record: docs/computer_use_system.md §2, §4, §7).
// The two must agree byte for byte on the same input: tests/fixtures/normalise_parity.json
// is generated by the Python side and replayed by test/normalise.test.js.
//
// Rule 1: data-shaped runs (emails, IBANs, cards, dates, phones, amounts, identifiers, digit
// runs) become class tokens. Rule 2: any word not in the app's control vocabulary — names that
// recur across at least MIN_SCREENS screens — becomes `{text}`. The leakage check enumerates
// exactly these tokens and fails on anything else.
import { APP_ROLES } from './workflows.js';

export const MIN_SCREENS = 2;
export const MAX_LEN = 255;
export const MIN_VALUE_LEN = 3;

const W = '\\p{L}\\p{N}_';
const MONTH = '(?:jan|feb|mar|apr|may|jun|jul|aug|sep|sept|oct|nov|dec)[a-z]*';
export const CLASS_PATTERNS = [
  ['email', new RegExp(`[${W}.+-]+@[${W}-]+\\.[${W}.-]+`, 'gu')],
  ['iban', /\b[A-Z]{2}\d{2}(?:\s?[A-Z0-9]{4}){2,7}(?:\s?[A-Z0-9]{1,4})?\b/gu],
  ['card', /\b(?:\d[ -]?){13,19}\b/gu],
  ['date', new RegExp(
    `\\b(?:\\d{4}-\\d{2}-\\d{2}(?:[T ]\\d{2}:\\d{2}(?::\\d{2})?)?` +
    `|\\d{1,2}[/.-]\\d{1,2}[/.-]\\d{2,4}` +
    `|\\d{1,2}\\s+${MONTH}\\.?,?\\s+\\d{2,4}` +
    `|${MONTH}\\.?\\s+\\d{1,2},?\\s+\\d{2,4})\\b`, 'giu')],
  ['phone', new RegExp(`(?<![${W}.])\\+?\\(?\\d[\\d\\s().-]{7,}\\d\\b`, 'gu')],
  ['amount', /(?:[$€£¥]\s?-?\d[\d,]*(?:\.\d+)?|-?\d[\d,]*\.\d{2}\b|\b\d[\d,]*\s?(?:USD|EUR|GBP|CHF)\b)/gu],
  ['id', /\b(?=[A-Za-z0-9#_-]*\d)(?=[A-Za-z0-9#_-]*[A-Za-z#])[A-Za-z0-9#_-]{3,}\b/gu],
  ['number', /\d+/gu],
];
export const TOKENS = new Set([...CLASS_PATTERNS.map(([n]) => `{${n}}`), '{text}']);
const TOKEN = /^\{[a-z]+\}$/;
const ANY_TOKEN = /\{[a-z_]+\}/g;
const WORD = new RegExp(`\\{[a-z]+\\}|[\\p{L}\\p{N}]+(?:['’][\\p{L}\\p{N}]+)?`, 'gu');
const HASH = /^[0-9a-f]{8,64}$/;
const SLOT_PREFIX = /^(?:doc|rec|field|fact|dialog|have|read|open|in|ctx):/;
// Landmark roles are a closed vocabulary (taskmining.leakage.LANDMARK_ROLES), not app names.
export const LANDMARK_ROLES = new Set(['banner', 'navigation', 'main', 'complementary', 'contentinfo', 'search', 'form', 'region', 'dialog', 'alertdialog', 'toolbar', 'tablist']);
// Keys and shortcut combos are a closed set: they name no data and pass as themselves.
const KEY_NAMES = new Set(['enter', 'return', 'tab', 'escape', 'esc', 'backspace', 'delete', 'space', 'up', 'down', 'left', 'right', 'home', 'end', 'pageup', 'pagedown', 'insert', 'capslock']);
const KEY_COMBO = /^(?:(?:cmd|ctrl|alt|shift|meta|option|win|super|fn)\+)+(?:[a-z0-9]|f\d{1,2}|enter|return|tab|escape|esc|backspace|delete|space|up|down|left|right|home|end|pageup|pagedown|insert)$/;
export const NAME_KEYS = new Set(['name', 'control', 'activity', 'label', 'title', 'descriptor', 'aliases', 'landmark']);

export const KNOWN_LIMITS = [
  'A single lower-case surname that recurs across screens is indistinguishable from a control name and joins the vocabulary.',
  'Non-Latin scripts get no class detection; they pass through the vocabulary rule only.',
  'Letters-only identifiers (a customer code such as `ACME`) are words to the normaliser; they leave only via the vocabulary.',
];

/** A key name or shortcut combo in canonical form (`cmd+s`, `enter`), or null if it is not one. */
export function keyName(text) {
  const k = String(text ?? '').trim().toLowerCase().replace(/\s+/g, '');
  if (!k) return null;
  if (KEY_NAMES.has(k) || /^f\d{1,2}$/.test(k) || k.length === 1 || KEY_COMBO.test(k)) return k;
  return null;
}

/** Rule 1 only: replace data-shaped runs with class tokens. Case and spacing untouched. */
export function classify(text) {
  let out = String(text ?? '');
  for (const [name, re] of CLASS_PATTERNS) out = out.replace(re, `{${name}}`);
  return out;
}

/** The lower-cased words of `text` (class tokens count as one word). */
export function words(text) {
  return [...String(text ?? '').matchAll(WORD)].map((m) => m[0].toLowerCase());
}

/**
 * Words allowed to leave the device as themselves: control names that recur across screens.
 * Built incrementally — `addScreen(names)` once per screen (or record) — so a run can grow a
 * session vocabulary the same way the compiler grows a recording's.
 */
export class Vocabulary {
  constructor({ minScreens = MIN_SCREENS, extra = [], words: known = [] } = {}) {
    this.minScreens = minScreens;
    this.screens = 0;
    this.seen = new Map();
    this.known = new Set(known.map((w) => String(w).toLowerCase()));
    this.extra = new Set(extra.flatMap((e) => words(classify(e))).filter((w) => !TOKEN.test(w)));
    this.method = 'recurring-ax-names/1';
  }

  static build(screens, opts = {}) {
    const v = new Vocabulary(opts);
    for (const names of screens) v.addScreen(names);
    return v;
  }

  addScreen(names) {
    this.screens += 1;
    const per = new Set();
    for (const name of names) for (const w of words(classify(name))) if (!TOKEN.test(w)) per.add(w);
    for (const w of per) this.seen.set(w, (this.seen.get(w) ?? 0) + 1);
    return this;
  }

  has(word) {
    const w = String(word).toLowerCase();
    return this.known.has(w) || this.extra.has(w) || (this.seen.get(w) ?? 0) >= this.minScreens;
  }

  get words() {
    const out = new Set(this.known);
    for (const [w, c] of this.seen) if (c >= this.minScreens) out.add(w);
    return [...out].sort();
  }

  toJSON() {
    const w = this.words, extra = [...this.extra].sort();
    return { method: this.method, min_screens: this.minScreens, screens: this.screens, size: w.length + extra.length, words: w, extra };
  }
}

/** Both rules. Lower-case, single-spaced, at most MAX_LEN characters; with no vocabulary every word is data. */
export function normalise(text, vocab = null) {
  const parts = [];
  for (const w of words(classify(text))) {
    if (TOKEN.test(w)) parts.push(w);
    else if (vocab && vocab.has(w)) parts.push(w);
    else if (parts.length && parts[parts.length - 1] === '{text}') continue;
    else parts.push('{text}');
  }
  return parts.join(' ').replace(/\s+/g, ' ').trim().slice(0, MAX_LEN);
}

/** A table row is named from its column headers and its position, never from its cells. */
export function rowName(headers, position, vocab = null) {
  const heads = headers.map((h) => normalise(h, vocab)).filter((h) => h && h !== '{text}').slice(0, 4);
  return `row ${position} of (${heads.join(', ') || 'table'})`;
}

/** True when the normalised text still says something (not only `{text}`). */
export function informative(text) {
  return !!text && text.split(' ').some((w) => w !== '{text}');
}

// ---- leakage check ---------------------------------------------------------------------------------
// Twin of taskmining.leakage.check: a payload fails when any string in it contains a value the
// recording saw, a window title, a token the normaliser does not produce, or (on the keys that
// name things) a word outside the vocabulary. The report never repeats the value.

const keep = (s) => typeof s === 'string' && s.trim().length >= MIN_VALUE_LEN;

/** What the recording knows and must not leak; comparisons are case-insensitive. */
export function recordingContext({ values = [], titles = [], vocab = null } = {}) {
  return {
    values: new Set(values.filter(keep).map((v) => v.trim().toLowerCase())),
    titles: new Set(titles.filter(keep).map((t) => t.trim().toLowerCase())),
    vocab,
  };
}

function* strings(payload, path = '$') {
  if (typeof payload === 'string') yield [path, path.split('.').pop().split('[')[0], payload];
  else if (Array.isArray(payload)) for (let i = 0; i < payload.length; i++) yield* strings(payload[i], `${path}[${i}]`);
  else if (payload && typeof payload === 'object') for (const [k, v] of Object.entries(payload)) yield* strings(v, `${path}.${k}`);
}

const exempt = (value) => HASH.test(value) || SLOT_PREFIX.test(value) || APP_ROLES.has(value) || LANDMARK_ROLES.has(value) || keyName(value) === value;

export function checkLeakage(payload, ctx) {
  const failures = [];
  let n = 0;
  for (const [path, key, value] of strings(payload)) {
    n += 1;
    const low = value.toLowerCase();
    for (const v of ctx.values) if (low.includes(v)) { failures.push({ path, reason: 'recorded_value', length: v.length }); break; }
    for (const t of ctx.titles) if (low.includes(t)) { failures.push({ path, reason: 'window_title', length: t.length }); break; }
    for (const tok of value.match(ANY_TOKEN) ?? []) if (!TOKENS.has(tok)) failures.push({ path, reason: 'unknown_token', length: tok.length });
    if (NAME_KEYS.has(key) && ctx.vocab && !exempt(value)) {
      const bad = words(value).filter((w) => !TOKEN.test(w) && !ctx.vocab.has(w));
      if (bad.length) failures.push({ path, reason: 'non_vocab_name', length: bad.length });
    }
  }
  return { ok: !failures.length, failures, strings_checked: n, known_limits: KNOWN_LIMITS };
}

/** One line for an error message: reasons and paths, never values. */
export function describeFailures(report, limit = 5) {
  return report.failures.slice(0, limit).map((f) => `${f.reason} at ${f.path}`).join('; ') + (report.failures.length > limit ? ` (+${report.failures.length - limit} more)` : '');
}
