const { contextBridge, ipcRenderer } = require('electron');

const on = (channel) => (fn) => {
  const h = (_e, ...args) => fn(...args);
  ipcRenderer.on(channel, h);
  return () => ipcRenderer.off(channel, h);
};

contextBridge.exposeInMainWorld('vista', {
  start: () => ipcRenderer.invoke('rec:start'),
  setIntent: (text) => ipcRenderer.invoke('rec:intent', text),
  pause: () => ipcRenderer.invoke('rec:pause'),
  resume: () => ipcRenderer.invoke('rec:resume'),
  stop: () => ipcRenderer.invoke('rec:stop'),
  toggle: () => ipcRenderer.invoke('rec:toggle'),
  status: () => ipcRenderer.invoke('rec:status'),
  onStatus: on('rec:status'),
  recordings: () => ipcRenderer.invoke('recordings:list'),
  onRecordings: on('recordings:changed'),
  openRecording: (id) => ipcRenderer.invoke('recordings:open', id),
  openWorkspace: (id) => ipcRenderer.invoke('recordings:open-workspace', id),
  annotate: (id, ann) => ipcRenderer.invoke('recordings:annotate', id, ann),
  sections: (id) => ipcRenderer.invoke('recordings:sections', id),
  onSections: on('recordings:sections'),
  explain: (id, opts) => ipcRenderer.invoke('recordings:explain', id, opts),
  decide: (id, itemId, action, body) => ipcRenderer.invoke('recordings:decide', id, itemId, action, body),
  editSection: (id, sectionId, patch) => ipcRenderer.invoke('recordings:edit-section', id, sectionId, patch),
  excludeSection: (id, sectionId, excluded) => ipcRenderer.invoke('recordings:exclude-section', id, sectionId, excluded),
  plan: (id) => ipcRenderer.invoke('recordings:plan', id),
  editPlan: (id, edgeId, patch) => ipcRenderer.invoke('recordings:edit-plan', id, edgeId, patch),
  decideFlag: (id, flagId, decision) => ipcRenderer.invoke('recordings:flag', id, flagId, decision),
  approveInsights: (id, approved) => ipcRenderer.invoke('recordings:approve-insights', id, approved),
  rerunAgents: (id) => ipcRenderer.invoke('recordings:rerun-agents', id),
  onOverlayCollapse: on('overlay:collapse'),
  toggleFile: (id, fileId, include) => ipcRenderer.invoke('recordings:toggle-file', id, fileId, include),
  openFile: (id, fileId) => ipcRenderer.invoke('recordings:open-file', id, fileId),
  submit: (id, options) => ipcRenderer.invoke('recordings:submit', id, options),
  uploadPreview: (id) => ipcRenderer.invoke('recordings:upload-preview', id),
  analysis: (id) => ipcRenderer.invoke('recordings:analysis', id),
  answerQuestions: (id, answers) => ipcRenderer.invoke('recordings:answer', id, answers),
  publishReport: (id, options) => ipcRenderer.invoke('recordings:publish', id, options),
  reanalyze: (id) => ipcRenderer.invoke('recordings:reanalyze', id),
  retryUploads: () => ipcRenderer.invoke('cloud:retry'),
  openDashboard: () => ipcRenderer.invoke('dashboard:open'),
  resizeOverlay: (mode) => ipcRenderer.invoke('overlay:resize', mode),
  onReview: on('dashboard:review'),
  getSettings: () => ipcRenderer.invoke('settings:get'),
  setSettings: (patch) => ipcRenderer.invoke('settings:set', patch),
  defaultSettings: () => ipcRenderer.invoke('settings:defaults'),
  info: () => ipcRenderer.invoke('app:info'),
  relaunch: () => ipcRenderer.invoke('app:relaunch'),
  workflows: (id) => ipcRenderer.invoke('recordings:workflows', id),
  permissions: () => ipcRenderer.invoke('permissions:get'),
  openPermission: (kind) => ipcRenderer.invoke('permissions:open', kind),
  onPermissions: on('permissions:changed'),
  cloudStatus: () => ipcRenderer.invoke('cloud:status'),
  cuStatus: () => ipcRenderer.invoke('cu:status'),
  cuList: () => ipcRenderer.invoke('cu:list'),
  cuStart: (runId, options) => ipcRenderer.invoke('cu:start', runId, options),
  cuStop: (reason) => ipcRenderer.invoke('cu:stop', reason),
  cuSteps: (sessionId) => ipcRenderer.invoke('cu:steps', sessionId),
  onCuStatus: on('cu:status'),
  cloudDiscover: (input) => ipcRenderer.invoke('cloud:discover', input),
  cloudConnect: (input) => ipcRenderer.invoke('cloud:connect', input),
  cloudDisconnect: () => ipcRenderer.invoke('cloud:disconnect'),
  cloudUpload: (id) => ipcRenderer.invoke('cloud:upload', id),
  // capture window only
  onVideoStart: on('video:start'),
  onVideoPause: on('video:pause'),
  onVideoResume: on('video:resume'),
  onVideoStop: on('video:stop'),
  videoChunk: (dir, buf) => ipcRenderer.send('video:chunk', dir, buf),
  videoDone: () => ipcRenderer.send('video:done'),
});
