(function () {
  const { rows, sum, count, money, fmtInt, num } = VistaUI;
  const T = VISTA_DATA.tables;

  VistaUI.mount({
    nav: '#nav', content: '#content',
    modules: [
      { id: 'home', group: 'Menu', label: 'Home',
        kpis: [
          { label: 'Open sales orders', value: () => fmtInt(count(rows('sales_orders'), (o) => o['Order Status'] !== 'Closed' && o['Order Status'] !== 'Cancelled')) },
          { label: 'Sales order value', value: () => money(sum(rows('sales_orders'), 'Order Total')) },
          { label: 'Open POs', value: () => fmtInt(count(rows('purchase_orders'), (p) => p['Po Status'] === 'Open')) },
          { label: 'Inventory value (xlsx)', value: () => money(sum(rows('inventory_balances'), 'Extended Value')) },
          { label: 'Open AR (xlsx)', value: () => money(sum(rows('ar_aging'), 'Balance')) },
          { label: 'Open AP', value: () => money(sum(rows('ap_aging'), 'Open Amount')) },
        ],
        tables: [
          { title: 'Reminders: orders on credit hold', table: 'sales_orders', filter: (o) => o['Credit Hold'] === 'Y', columns: ['So Number', 'Customer Id', 'Customer Po Number', 'Order Date', 'Order Total', 'Order Status'] },
          { title: 'Recent activity', table: 'workflow_events', columns: ['Timestamp', 'Workflow Type', 'Object Id', 'Actor', 'Action', 'New State', 'Requires Review'] },
        ] },
      { id: 'customers', group: 'Menu', label: 'Customers',
        kpis: [
          { label: 'Customers', value: () => fmtInt(rows('customers').length) },
          { label: 'Contacts', value: () => fmtInt(rows('customer_contacts').length) },
          { label: 'On credit hold', value: () => fmtInt(count(rows('customers'), (c) => c['Credit Hold'] === 'Y')) },
        ],
        tables: [
          { title: 'Customer list', table: 'customers', columns: ['Customer Id', 'Customer Name', 'Segment', 'Bill To City', 'Bill To State', 'Payment Terms', 'Credit Limit', 'Credit Hold', 'Sales Rep Id', 'Price Level', 'Status'],
            detail: { key: 'Customer Id', titleCol: 'Customer Name', related: [
              { table: 'customer_contacts', fk: 'Customer Id', title: 'Contacts', columns: ['Full Name', 'Title', 'Email', 'Phone'] },
              { table: 'ship_to_locations', fk: 'Customer Id', title: 'Ship-to', columns: ['Name', 'City', 'State'] },
              { table: 'sales_orders', fk: 'Customer Id', title: 'Sales orders', columns: ['So Number', 'Customer Po Number', 'Order Date', 'Order Total', 'Order Status'] },
              { table: 'customer_price_agreements', fk: 'Customer Id', title: 'Price agreements', columns: ['Item Id', 'Contract Price', 'Expiration Date'] },
              { table: 'ar_aging', fk: 'Customer Id', title: 'Open AR', columns: ['Invoice Number', 'Due Date', 'Days Past Due', 'Balance'] },
            ] } },
          { title: 'Contacts', table: 'customer_contacts' },
          { title: 'Ship-to locations', table: 'ship_to_locations' },
        ] },
      { id: 'sales', group: 'Menu', label: 'Sales',
        kpis: [
          { label: 'RFQs', value: () => fmtInt(rows('rfqs').length) },
          { label: 'Quotes', value: () => fmtInt(rows('sales_quotes').length) },
          { label: 'Sales orders', value: () => fmtInt(T.sales_orders.total) },
          { label: 'Shipments', value: () => fmtInt(T.shipments.total) },
        ],
        tables: [
          { title: 'Sales orders', table: 'sales_orders', columns: ['So Number', 'Customer Id', 'Customer Po Number', 'Order Date', 'Sales Rep Id', 'Order Source', 'Order Total', 'Credit Hold', 'Order Status', 'Invoiced'],
            detail: { key: 'So Number', related: [
              { table: 'sales_order_lines', fk: 'So Number', title: 'Lines', columns: ['Line', 'Item Id', 'Description', 'Qty', 'Price', 'Extended Price', 'Promised Date', 'Line Status'] },
              { table: 'credit_checks', fk: 'So Number', title: 'Credit check', columns: ['Check Date', 'Credit Limit', 'Open Ar At Check', 'Result'] },
              { table: 'shipments', fk: 'So Number', title: 'Shipments', columns: ['Shipment Id', 'Ship Date', 'Carrier', 'Tracking Number', 'Status'] },
              { table: 'customer_invoices', fk: 'So Number', title: 'Invoices', columns: ['Invoice Number', 'Invoice Date', 'Invoice Total', 'Balance', 'Status'] },
            ] } },
          { title: 'RFQs', table: 'rfqs' },
          { title: 'Quotes', table: 'sales_quotes', detail: { key: 'Quote Id', related: [{ table: 'sales_quote_lines', fk: 'Quote Id', title: 'Lines' }] } },
          { title: 'Order changes', table: 'order_changes' },
        ] },
      { id: 'items', group: 'Menu', label: 'Items',
        kpis: [
          { label: 'Items', value: () => fmtInt(rows('items').length) },
          { label: 'Price list rows', value: () => fmtInt(rows('price_lists').length) },
          { label: 'BOM lines', value: () => fmtInt(rows('bills_of_material').length) },
        ],
        tables: [
          { title: 'Item list', table: 'items', columns: ['Item Id', 'Description', 'Item Class', 'Manufacturer', 'Primary Supplier', 'Unit Cost', 'List Price', 'Abc Class', 'Reorder Point', 'Lead Time Days', 'Make Or Buy', 'Status'],
            detail: { key: 'Item Id', titleCol: 'Description', related: [
              { table: 'inventory_balances', fk: 'Item Id', title: 'Inventory', columns: ['Warehouse', 'Bin Location', 'On Hand Qty', 'Available Qty', 'Unit Cost'] },
              { table: 'price_lists', fk: 'Item Id', title: 'Price lists', columns: ['Price Level', 'Unit Price', 'Effective Date'] },
              { table: 'supplier_quotes', fk: 'Item Id', title: 'Supplier quotes', columns: ['Supplier Id', 'Quoted Unit Cost', 'Lead Time Days', 'Awarded'] },
              { table: 'bills_of_material', fk: 'Parent Item Id', title: 'BOM', columns: ['Component Item Id', 'Qty Per', 'Uom'] },
              { table: 'trade_compliance', fk: 'Item Id', title: 'Trade compliance', columns: ['Hts Code', 'Country Of Origin', 'Duty Rate Pct'] },
            ] } },
          { title: 'Price lists', table: 'price_lists' },
          { title: 'Bills of material', table: 'bills_of_material' },
          { title: 'Units of measure', table: 'units_of_measure' },
        ] },
      { id: 'purchasing', group: 'Menu', label: 'Purchasing',
        kpis: [
          { label: 'Suppliers', value: () => fmtInt(rows('suppliers').length) },
          { label: 'PO spend', value: () => money(sum(rows('purchase_orders'), 'Po Total')) },
          { label: '3-way match exceptions', value: () => fmtInt(count(rows('three_way_match'), (m) => m.Result !== 'Matched')) },
          { label: 'Open AP', value: () => money(sum(rows('ap_aging'), 'Open Amount')) },
        ],
        tables: [
          { title: 'Purchase orders', table: 'purchase_orders', detail: { key: 'Po Number', related: [
              { table: 'purchase_order_lines', fk: 'Po Number', title: 'Lines', columns: ['Line', 'Item Id', 'Description', 'Ordered Qty', 'Price', 'Extended Cost', 'Received Qty', 'Line Status'] },
              { table: 'receipts', fk: 'Po Number', title: 'Receipts', columns: ['Receipt Id', 'Receipt Date', 'Packing Slip Number', 'Condition'] },
              { table: 'supplier_invoices', fk: 'Po Number', title: 'Bills', columns: ['Supplier Invoice Number', 'Invoice Date', 'Invoice Total', 'Status', 'Match Status'] },
            ] } },
          { title: 'Vendors (suppliers)', table: 'suppliers', note: 'Duplicate supplier records exist in this export.', detail: { key: 'Supplier Id', titleCol: 'Supplier Name', related: [
              { table: 'supplier_contacts', fk: 'Supplier Id', title: 'Contacts' },
              { table: 'supplier_scorecards', fk: 'Supplier Id', title: 'Scorecards', columns: ['Period', 'On Time Delivery Pct', 'Quality Ppm', 'Overall Rating'] },
              { table: 'purchase_orders', fk: 'Supplier Id', title: 'POs', columns: ['Po Number', 'Po Date', 'Po Total', 'Po Status'] },
            ] } },
          { title: 'Purchase requisitions', table: 'purchase_requisitions' },
          { title: 'Supplier quotes', table: 'supplier_quotes' },
          { title: 'Supplier scorecards', table: 'supplier_scorecards' },
          { title: 'Three-way match', table: 'three_way_match' },
          { title: 'Vendor bills', table: 'supplier_invoices' },
          { title: 'AP aging', table: 'ap_aging' },
          { title: 'Bill payments', table: 'ap_payments' },
        ] },
      { id: 'inventory', group: 'Menu', label: 'Inventory',
        kpis: [
          { label: 'Stocked SKUs', value: () => fmtInt(rows('inventory_balances').length) },
          { label: 'Inventory value', value: () => money(sum(rows('inventory_balances'), 'Extended Value')) },
          { label: 'Count variance $', value: () => money(sum(rows('cycle_counts'), 'Variance Value')) },
        ],
        tables: [
          { title: 'Inventory balances (Excel export)', table: 'inventory_balances' },
          { title: 'Cycle counts', table: 'cycle_counts' },
          { title: 'Inventory transactions', table: 'inventory_transactions' },
          { title: 'Reorder parameters', table: 'reorder_parameters' },
          { title: 'Transfers', table: 'transfers' },
          { title: 'Lot traceability', table: 'lot_traceability' },
        ] },
      { id: 'fulfillment', group: 'Menu', label: 'Fulfillment',
        tables: [
          { title: 'Shipments', table: 'shipments', detail: { key: 'Shipment Id', related: [{ table: 'pick_lists', fk: 'Shipment Id', title: 'Picks' }, { table: 'bills_of_lading', fk: 'Shipment Id', title: 'BOL' }, { table: 'freight_invoices', fk: 'Shipment Id', title: 'Freight invoice' }, { table: 'proof_of_delivery', fk: 'Shipment Id', title: 'POD' }] } },
          { title: 'Pick lists', table: 'pick_lists' },
          { title: 'Freight invoices', table: 'freight_invoices' },
          { title: 'MRP recommendations', table: 'mrp_recommendations' },
          { title: 'Demand forecast', table: 'demand_forecast' },
        ] },
      { id: 'mfg', group: 'Menu', label: 'Assembly & Quality',
        kpis: [
          { label: 'Work orders', value: () => fmtInt(rows('work_orders').length) },
          { label: 'Inspections', value: () => fmtInt(rows('inspections').length) },
          { label: 'NCRs', value: () => fmtInt(rows('nonconformance_reports').length) },
          { label: 'Maintenance WOs', value: () => fmtInt(rows('maintenance_work_orders').length) },
        ],
        tables: [
          { title: 'Work orders (light assembly)', table: 'work_orders', detail: { key: 'Work Order Id', related: [{ table: 'material_issues', fk: 'Work Order Id', title: 'Material issues' }, { table: 'production_completions', fk: 'Work Order Id', title: 'Completions' }, { table: 'certificates_of_conformance', fk: 'Work Order Id', title: 'CoCs' }] } },
          { title: 'Routings', table: 'routings' },
          { title: 'Inspections', table: 'inspections' },
          { title: 'Nonconformance reports', table: 'nonconformance_reports' },
          { title: 'Corrective actions', table: 'corrective_actions' },
          { title: 'Equipment', table: 'equipment' },
          { title: 'Maintenance work orders', table: 'maintenance_work_orders' },
        ] },
      { id: 'ar', group: 'Menu', label: 'Receivables',
        kpis: [
          { label: 'Invoices', value: () => fmtInt(T.customer_invoices.total) },
          { label: 'Open AR', value: () => money(sum(rows('ar_aging'), 'Balance')) },
          { label: 'Past due > 60', value: () => money(sum(rows('ar_aging').filter((a) => num(a['Days Past Due']) > 60), 'Balance')) },
          { label: 'Open RMAs', value: () => fmtInt(count(rows('rmas'), (r) => r.Status !== 'Closed')) },
        ],
        tables: [
          { title: 'AR aging (Excel export)', table: 'ar_aging' },
          { title: 'Invoices', table: 'customer_invoices', detail: { key: 'Invoice Number', related: [{ table: 'customer_invoice_lines', fk: 'Invoice Number', title: 'Lines' }, { table: 'customer_payments', fk: 'Applied To Invoice', title: 'Payments' }, { table: 'disputes_deductions', fk: 'Invoice Number', title: 'Disputes' }] } },
          { title: 'Customer payments', table: 'customer_payments' },
          { title: 'Disputes & deductions', table: 'disputes_deductions' },
          { title: 'RMAs', table: 'rmas' },
          { title: 'Field service orders', table: 'field_service_orders' },
        ] },
      { id: 'financial', group: 'Menu', label: 'Financial',
        kpis: [
          { label: 'GL entries', value: () => fmtInt(T.general_ledger.total) },
          { label: 'Software spend / yr', value: () => money(sum(rows('software_subscriptions'), 'Annual Cost')) },
          { label: 'Indirect AP', value: () => money(sum(rows('ap_vendor_invoices_indirect'), 'Amount')) },
        ],
        tables: [
          { title: 'Budget vs actual', table: 'budget_vs_actual' },
          { title: 'General ledger', table: 'general_ledger' },
          { title: 'Cost variances', table: 'cost_variances' },
          { title: 'Inventory valuation', table: 'inventory_valuation' },
          { title: 'Indirect vendor bills', table: 'ap_vendor_invoices_indirect' },
          { title: 'Corporate vendors', table: 'corporate_vendors' },
          { title: 'Software subscriptions', table: 'software_subscriptions' },
          { title: 'Chart of accounts', table: 'chart_of_accounts' },
          { title: 'Operating bank statement', table: 'bank_statement_operating' },
          { title: 'Customs entries', table: 'customs_entries' },
          { title: 'Trade compliance', table: 'trade_compliance' },
        ] },
      { id: 'hr', group: 'Menu', label: 'Employees',
        tables: [
          { title: 'Employees', table: 'employees', detail: { key: 'Employee Id', titleCol: 'Full Name', related: [{ table: 'payroll_register', fk: 'Employee Id', title: 'Payroll' }, { table: 'pto_balances', fk: 'Employee Id', title: 'PTO' }, { table: 'training_certifications', fk: 'Employee Id', title: 'Training' }] } },
          { title: 'EHS incidents', table: 'ehs_incidents' },
          { title: 'Training & certifications', table: 'training_certifications' },
          { title: 'Payroll register', table: 'payroll_register' },
        ] },
      { id: 'docs', group: 'Menu', label: 'Documents', docs: true, tables: [{ title: 'Document index', table: 'document_index' }] },
      { id: 'explorer', group: 'Menu', label: 'All Files', explorer: true },
    ],
  });
})();
