"""Bundle each company's synthetic datasets into a static `data.js` for its demo front end.

    python3 synthetic_data/front_end_work/build_data.py

Each front end folder gets a `data.js` defining `window.VISTA_DATA` with:
  company   -> parsed 00_company/company_profile.json
  tables    -> {dataset_name: {columns, rows, source, total}}  (CSV files + XLSX sheets)
  docs      -> {file_name: {source, text}}  (eml / txt / md / json documents)
Rows are capped at MAX_ROWS per table so the bundles stay small enough to open from file://.
"""
from __future__ import annotations

import csv
import json
import os
import sys

import openpyxl

HERE = os.path.dirname(os.path.abspath(__file__))
SYN = os.path.dirname(HERE)
MAX_ROWS = 400

COMPANIES = {
    "meridian_risk_partners": "insurance_broking",
    "harborline_insurance_brokers": "insurance_broking",
    "castlebrook_agency": "insurance_broking",
    "northfield_industrial_components": "industrial_goods",
    "keystone_bearing_and_drive": "industrial_goods",
    "ridgeway_fasteners_and_supply": "industrial_goods",
}


def load_csv(path: str) -> tuple[list[str], list[list[str]], int]:
    with open(path, newline="", encoding="utf-8") as f:
        reader = csv.reader(f)
        rows = list(reader)
    if not rows:
        return [], [], 0
    return rows[0], rows[1 : MAX_ROWS + 1], len(rows) - 1


def load_xlsx(path: str) -> dict[str, tuple[list[str], list[list], int]]:
    wb = openpyxl.load_workbook(path, read_only=True, data_only=True)
    out = {}
    for ws in wb.worksheets:
        rows = [["" if v is None else v for v in r] for r in ws.iter_rows(values_only=True)]
        if not rows:
            continue
        header = [str(h) for h in rows[0]]
        body = [[v.isoformat() if hasattr(v, "isoformat") else v for v in r] for r in rows[1 : MAX_ROWS + 1]]
        out[ws.title] = (header, body, len(rows) - 1)
    return out


def bundle(slug: str, sector: str) -> dict:
    root = os.path.join(SYN, sector, slug)
    data: dict = {"slug": slug, "sector": sector, "company": {}, "tables": {}, "docs": {}}
    for dirpath, _, files in os.walk(root):
        for fn in sorted(files):
            full = os.path.join(dirpath, fn)
            rel = os.path.relpath(full, root).replace(os.sep, "/")
            name, ext = os.path.splitext(fn)
            ext = ext.lower()
            if rel == "00_company/company_profile.json":
                with open(full, encoding="utf-8") as f:
                    data["company"] = json.load(f)
            elif ext == ".csv":
                cols, rows, total = load_csv(full)
                data["tables"][name] = {"columns": cols, "rows": rows, "source": rel, "total": total}
            elif ext == ".xlsx":
                for sheet, (cols, rows, total) in load_xlsx(full).items():
                    key = sheet if sheet not in data["tables"] else f"{name}:{sheet}"
                    data["tables"][key] = {"columns": cols, "rows": rows, "source": f"{rel}#{sheet}", "total": total, "legacy_workbook": True}
            elif ext in (".eml", ".txt", ".md", ".json"):
                with open(full, encoding="utf-8") as f:
                    data["docs"][fn] = {"source": rel, "text": f.read()}
    return data


def main() -> None:
    for slug, sector in COMPANIES.items():
        data = bundle(slug, sector)
        out_dir = os.path.join(HERE, slug)
        os.makedirs(out_dir, exist_ok=True)
        out = os.path.join(out_dir, "data.js")
        with open(out, "w", encoding="utf-8") as f:
            f.write("// Generated by front_end_work/build_data.py — do not edit by hand.\n")
            f.write("window.VISTA_DATA = ")
            json.dump(data, f, separators=(",", ":"), default=str)
            f.write(";\n")
        size_kb = os.path.getsize(out) // 1024
        print(f"{slug:36s} tables={len(data['tables']):3d} docs={len(data['docs']):2d} {size_kb:5d} KB")


if __name__ == "__main__":
    sys.exit(main())
