(function () {
  const { rows, sum, count, money, fmtInt, num } = VistaUI;
  const T = VISTA_DATA.tables;

  VistaUI.mount({
    nav: '#nav', content: '#content',
    modules: [
      { id: 'home', group: 'Plant', label: 'Operations Overview', icon: '◉',
        description: 'Northfield Industrial Components, Inc. · Rockford, IL · Make-to-order + make-to-stock · Epicor Kinetic',
        kpis: [
          { label: 'Open sales orders', value: () => fmtInt(count(rows('sales_orders'), (o) => o.order_status === 'Open' || o.order_status === 'Partially Shipped')) },
          { label: 'Order book (all)', value: () => money(sum(rows('sales_orders'), 'order_total')) },
          { label: 'Released work orders', value: () => fmtInt(count(rows('work_orders'), (w) => w.status !== 'Closed')) },
          { label: 'Open NCRs', value: () => fmtInt(count(rows('nonconformance_reports'), (n) => n.status !== 'Closed')) },
          { label: 'Inventory value', value: () => money(sum(rows('inventory_balances'), 'extended_value')) },
          { label: 'AR balance', value: () => money(sum(rows('ar_aging'), 'balance')) },
        ],
        tables: [
          { title: 'Late / due work orders', table: 'work_orders', filter: (w) => w.status !== 'Closed', columns: ['work_order_id', 'item_id', 'order_qty', 'release_date', 'due_date', 'demand_source', 'status', 'completed_qty', 'scrap_qty'] },
          { title: 'Workflow event stream', table: 'workflow_events', columns: ['timestamp', 'workflow_type', 'object_id', 'actor', 'action', 'previous_state', 'new_state', 'requires_review'] },
        ] },
      { id: 'customers', group: 'Commercial', label: 'Customers', icon: '☷',
        kpis: [
          { label: 'Customers', value: () => fmtInt(rows('customers').length) },
          { label: 'On credit hold', value: () => fmtInt(count(rows('customers'), (c) => c.credit_hold === 'Y')) },
          { label: 'Ship-to sites', value: () => fmtInt(rows('ship_to_locations').length) },
          { label: 'Price agreements', value: () => fmtInt(rows('customer_price_agreements').length) },
        ],
        tables: [
          { title: 'Customer master', table: 'customers', columns: ['customer_id', 'customer_name', 'segment', 'bill_to_city', 'bill_to_state', 'payment_terms', 'credit_limit', 'credit_hold', 'sales_rep_id', 'price_level', 'customer_since', 'status'],
            detail: { key: 'customer_id', titleCol: 'customer_name', related: [
              { table: 'customer_contacts', fk: 'customer_id', title: 'Contacts', columns: ['full_name', 'title', 'email', 'phone', 'role'] },
              { table: 'ship_to_locations', fk: 'customer_id', title: 'Ship-to locations', columns: ['name', 'city', 'state', 'dock_hours'] },
              { table: 'sales_orders', fk: 'customer_id', title: 'Sales orders', columns: ['so_number', 'customer_po_number', 'order_date', 'order_total', 'order_status'] },
              { table: 'customer_price_agreements', fk: 'customer_id', title: 'Price agreements', columns: ['item_id', 'contract_price', 'min_qty', 'expiration_date'] },
              { table: 'ar_aging', fk: 'customer_id', title: 'Open AR', columns: ['invoice_number', 'due_date', 'days_past_due', 'balance', 'aging_bucket'] },
              { table: 'rmas', fk: 'customer_id', title: 'RMAs', columns: ['rma_number', 'item_id', 'reason_code', 'status'] },
            ] } },
          { title: 'Contacts', table: 'customer_contacts' },
          { title: 'Customer price agreements', table: 'customer_price_agreements' },
        ] },
      { id: 'sales', group: 'Commercial', label: 'Quote to Order', icon: '➚',
        kpis: [
          { label: 'RFQs', value: () => fmtInt(rows('rfqs').length) },
          { label: 'Quotes', value: () => fmtInt(rows('sales_quotes').length) },
          { label: 'Quote win rate', value: () => VistaUI.pct(count(rows('sales_quotes'), (q) => q.status === 'Won' || q.converted_order_id), rows('sales_quotes').length) },
          { label: 'Sales orders', value: () => fmtInt(T.sales_orders.total) },
        ],
        tables: [
          { title: 'Sales orders', table: 'sales_orders', columns: ['so_number', 'customer_id', 'customer_po_number', 'order_date', 'sales_rep_id', 'order_source', 'ship_via', 'order_total', 'credit_hold', 'order_status', 'invoiced'],
            detail: { key: 'so_number', related: [
              { table: 'sales_order_lines', fk: 'so_number', title: 'Lines', columns: ['line', 'item_id', 'description', 'ordered_qty', 'unit_price', 'extended_price', 'promised_date', 'shipped_qty', 'line_status'] },
              { table: 'credit_checks', fk: 'so_number', title: 'Credit check', columns: ['check_date', 'credit_limit', 'open_ar_at_check', 'result'] },
              { table: 'shipments', fk: 'so_number', title: 'Shipments', columns: ['shipment_id', 'ship_date', 'carrier', 'tracking_number', 'status'] },
              { table: 'customer_invoices', fk: 'so_number', title: 'Invoices', columns: ['invoice_number', 'invoice_date', 'invoice_total', 'balance', 'status'] },
              { table: 'order_changes', fk: 'so_number', title: 'Order changes', columns: ['change_date', 'change_type', 'old_value', 'new_value'] },
            ] } },
          { title: 'RFQs', table: 'rfqs' },
          { title: 'Sales quotes', table: 'sales_quotes', detail: { key: 'quote_id', related: [{ table: 'sales_quote_lines', fk: 'quote_id', title: 'Quote lines' }] } },
          { title: 'Order acknowledgments', table: 'order_acknowledgments' },
        ] },
      { id: 'items', group: 'Supply Chain', label: 'Item Master & BOMs', icon: '⚙',
        kpis: [
          { label: 'Items', value: () => fmtInt(rows('items').length) },
          { label: 'Make items', value: () => fmtInt(count(rows('items'), (i) => i.make_or_buy === 'Make')) },
          { label: 'BOM lines', value: () => fmtInt(rows('bills_of_material').length) },
          { label: 'Routings', value: () => fmtInt(rows('routings').length) },
        ],
        tables: [
          { title: 'Items', table: 'items', columns: ['item_id', 'description', 'item_class', 'manufacturer', 'stock_uom', 'primary_supplier', 'unit_cost', 'list_price', 'abc_class', 'reorder_point', 'lead_time_days', 'make_or_buy', 'status'],
            detail: { key: 'item_id', titleCol: 'description', related: [
              { table: 'bills_of_material', fk: 'parent_item_id', title: 'Bill of material', columns: ['line', 'component_item_id', 'qty_per', 'uom', 'scrap_pct', 'status'] },
              { table: 'routings', fk: 'item_id', title: 'Routing', columns: ['operation', 'work_center_id', 'description', 'setup_hours', 'run_hours_per_unit'] },
              { table: 'inventory_balances', fk: 'item_id', title: 'Inventory', columns: ['warehouse', 'bin_location', 'on_hand_qty', 'allocated_qty', 'available_qty', 'unit_cost'] },
              { table: 'price_lists', fk: 'item_id', title: 'Price lists', columns: ['price_level', 'unit_price', 'effective_date'] },
              { table: 'supplier_quotes', fk: 'item_id', title: 'Supplier quotes', columns: ['supplier_id', 'quoted_unit_cost', 'min_order_qty', 'lead_time_days', 'awarded'] },
              { table: 'item_revisions', fk: 'item_id', title: 'Revisions', columns: ['revision', 'eco_number', 'effective_date', 'drawing_number', 'status'] },
            ] } },
          { title: 'Bills of material', table: 'bills_of_material' },
          { title: 'Routings', table: 'routings' },
          { title: 'Work centers', table: 'work_centers' },
          { title: 'Standard cost roll', table: 'standard_cost_roll' },
        ] },
      { id: 'procurement', group: 'Supply Chain', label: 'Procurement', icon: '⇊',
        kpis: [
          { label: 'Suppliers', value: () => fmtInt(rows('suppliers').length) },
          { label: 'Open POs', value: () => fmtInt(count(rows('purchase_orders'), (p) => p.po_status === 'Open')) },
          { label: 'PO spend', value: () => money(sum(rows('purchase_orders'), 'po_total')) },
          { label: 'Avg on-time %', value: () => (sum(rows('supplier_scorecards'), 'on_time_delivery_pct') / Math.max(1, rows('supplier_scorecards').length)).toFixed(1) + '%' },
        ],
        tables: [
          { title: 'Purchase orders', table: 'purchase_orders', detail: { key: 'po_number', related: [
              { table: 'purchase_order_lines', fk: 'po_number', title: 'Lines', columns: ['line', 'item_id', 'description', 'ordered_qty', 'unit_cost', 'extended_cost', 'promised_date', 'received_qty', 'line_status'] },
              { table: 'po_acknowledgments', fk: 'po_number', title: 'Acknowledgment' },
              { table: 'receipts', fk: 'po_number', title: 'Receipts', columns: ['receipt_id', 'receipt_date', 'packing_slip_number', 'condition'] },
              { table: 'supplier_invoices', fk: 'po_number', title: 'Supplier invoices', columns: ['supplier_invoice_number', 'invoice_date', 'invoice_total', 'status', 'match_status'] },
            ] } },
          { title: 'Suppliers', table: 'suppliers', detail: { key: 'supplier_id', titleCol: 'supplier_name', related: [
              { table: 'supplier_contacts', fk: 'supplier_id', title: 'Contacts' },
              { table: 'supplier_scorecards', fk: 'supplier_id', title: 'Scorecards', columns: ['period', 'po_count', 'on_time_delivery_pct', 'quality_ppm', 'overall_rating'] },
              { table: 'supplier_contracts', fk: 'supplier_id', title: 'Contracts' },
              { table: 'purchase_orders', fk: 'supplier_id', title: 'Purchase orders', columns: ['po_number', 'po_date', 'po_total', 'po_status'] },
            ] } },
          { title: 'Purchase requisitions', table: 'purchase_requisitions' },
          { title: 'Supplier quotes', table: 'supplier_quotes' },
          { title: 'Supplier scorecards', table: 'supplier_scorecards' },
          { title: 'Supplier contracts', table: 'supplier_contracts' },
        ] },
      { id: 'receiving', group: 'Supply Chain', label: 'Receiving & AP', icon: '⇉',
        kpis: [
          { label: 'Receipts', value: () => fmtInt(T.receipts.total) },
          { label: 'Supplier invoices', value: () => fmtInt(T.supplier_invoices.total) },
          { label: '3-way match exceptions', value: () => fmtInt(count(rows('three_way_match'), (m) => m.result !== 'Matched')) },
          { label: 'Open AP', value: () => money(sum(rows('ap_aging'), 'open_amount')) },
        ],
        tables: [
          { title: 'Three-way match', table: 'three_way_match' },
          { title: 'Supplier invoices', table: 'supplier_invoices', detail: { key: 'supplier_invoice_number', related: [{ table: 'supplier_invoice_lines', fk: 'supplier_invoice_number', title: 'Lines' }, { table: 'ap_payments', fk: 'supplier_invoice_number', title: 'Payments' }] } },
          { title: 'Receipts', table: 'receipts', detail: { key: 'receipt_id', related: [{ table: 'receipt_lines', fk: 'receipt_id', title: 'Lines' }] } },
          { title: 'Advance ship notices', table: 'advance_ship_notices' },
          { title: 'AP aging', table: 'ap_aging' },
          { title: 'AP payments', table: 'ap_payments' },
        ] },
      { id: 'inventory', group: 'Supply Chain', label: 'Inventory & Warehouse', icon: '▦',
        kpis: [
          { label: 'Stocked SKUs', value: () => fmtInt(rows('inventory_balances').length) },
          { label: 'Inventory value', value: () => money(sum(rows('inventory_balances'), 'extended_value')) },
          { label: 'Cycle count variance $', value: () => money(sum(rows('cycle_counts'), 'variance_value')) },
          { label: 'Open shipments', value: () => fmtInt(count(rows('shipments'), (s) => s.status !== 'Delivered')) },
        ],
        tables: [
          { title: 'Inventory balances', table: 'inventory_balances' },
          { title: 'Cycle counts', table: 'cycle_counts' },
          { title: 'Inventory transactions', table: 'inventory_transactions' },
          { title: 'Lot traceability', table: 'lot_traceability' },
          { title: 'Reorder parameters', table: 'reorder_parameters' },
          { title: 'Shipments', table: 'shipments', detail: { key: 'shipment_id', related: [{ table: 'pick_lists', fk: 'shipment_id', title: 'Picks' }, { table: 'bills_of_lading', fk: 'shipment_id', title: 'BOL' }, { table: 'freight_invoices', fk: 'shipment_id', title: 'Freight invoice' }, { table: 'proof_of_delivery', fk: 'shipment_id', title: 'POD' }] } },
          { title: 'Freight invoices', table: 'freight_invoices' },
        ] },
      { id: 'planning', group: 'Plant', label: 'Demand Planning', icon: '↗',
        tables: [
          { title: 'MRP recommendations', table: 'mrp_recommendations' },
          { title: 'Demand forecast', table: 'demand_forecast' },
          { title: 'Reservations', table: 'reservations' },
        ] },
      { id: 'mfg', group: 'Plant', label: 'Manufacturing', icon: '⚒',
        kpis: [
          { label: 'Work orders', value: () => fmtInt(rows('work_orders').length) },
          { label: 'Open', value: () => fmtInt(count(rows('work_orders'), (w) => w.status !== 'Closed')) },
          { label: 'Labor hours', value: () => fmtInt(sum(rows('labor_transactions'), 'hours')) },
          { label: 'Scrap cost', value: () => money(sum(rows('scrap'), 'cost')) },
          { label: 'Downtime (min)', value: () => fmtInt(sum(rows('downtime'), 'minutes')) },
        ],
        tables: [
          { title: 'Work orders', table: 'work_orders', detail: { key: 'work_order_id', related: [
              { table: 'work_order_operations', fk: 'work_order_id', title: 'Operations', columns: ['operation', 'work_center_id', 'planned_run_hours', 'actual_run_hours', 'status'] },
              { table: 'material_issues', fk: 'work_order_id', title: 'Material issues', columns: ['issue_date', 'component_item_id', 'required_qty', 'issued_qty', 'lot_number'] },
              { table: 'labor_transactions', fk: 'work_order_id', title: 'Labor', columns: ['operation', 'employee_id', 'hours', 'labor_type'] },
              { table: 'production_completions', fk: 'work_order_id', title: 'Completions', columns: ['completion_date', 'completed_qty', 'std_cost', 'actual_cost', 'variance'] },
              { table: 'scrap', fk: 'work_order_id', title: 'Scrap' },
              { table: 'certificates_of_conformance', fk: 'work_order_id', title: 'CoCs', columns: ['coc_id', 'qty', 'issue_date', 'signed_by'] },
            ] } },
          { title: 'Production completions', table: 'production_completions' },
          { title: 'WIP balances', table: 'wip_balances' },
          { title: 'Downtime', table: 'downtime' },
          { title: 'Scrap', table: 'scrap' },
        ] },
      { id: 'quality', group: 'Plant', label: 'Quality', icon: '✓',
        kpis: [
          { label: 'Inspections', value: () => fmtInt(rows('inspections').length) },
          { label: 'Fail rate', value: () => VistaUI.pct(count(rows('inspections'), (i) => i.result === 'Fail'), rows('inspections').length) },
          { label: 'NCRs', value: () => fmtInt(rows('nonconformance_reports').length) },
          { label: 'Open CAPAs', value: () => fmtInt(count(rows('corrective_actions'), (c) => c.status !== 'Closed')) },
        ],
        tables: [
          { title: 'Nonconformance reports', table: 'nonconformance_reports', detail: { key: 'ncr_id', titleCol: 'description', related: [{ table: 'corrective_actions', fk: 'ncr_id', title: 'CAPA' }] } },
          { title: 'Inspections', table: 'inspections' },
          { title: 'Corrective actions', table: 'corrective_actions' },
          { title: 'Certificates of conformance', table: 'certificates_of_conformance' },
          { title: 'Calibration records', table: 'calibration_records' },
        ] },
      { id: 'maint', group: 'Plant', label: 'Maintenance', icon: '🔧',
        tables: [
          { title: 'Equipment', table: 'equipment', detail: { key: 'asset_id', titleCol: 'description', related: [{ table: 'maintenance_work_orders', fk: 'asset_id', title: 'Maintenance WOs' }, { table: 'pm_schedule', fk: 'asset_id', title: 'PM schedule' }] } },
          { title: 'Maintenance work orders', table: 'maintenance_work_orders' },
          { title: 'PM schedule', table: 'pm_schedule' },
        ] },
      { id: 'ar', group: 'Finance', label: 'Billing & AR', icon: '$',
        kpis: [
          { label: 'Invoices', value: () => fmtInt(T.customer_invoices.total) },
          { label: 'Open AR', value: () => money(sum(rows('ar_aging'), 'balance')) },
          { label: 'Past due > 60', value: () => money(sum(rows('ar_aging').filter((a) => num(a.days_past_due) > 60), 'balance')) },
          { label: 'Open disputes', value: () => fmtInt(count(rows('disputes_deductions'), (d) => d.status !== 'Closed')) },
        ],
        tables: [
          { title: 'AR aging', table: 'ar_aging' },
          { title: 'Customer invoices', table: 'customer_invoices', detail: { key: 'invoice_number', related: [{ table: 'customer_invoice_lines', fk: 'invoice_number', title: 'Lines' }, { table: 'customer_payments', fk: 'applied_to_invoice', title: 'Payments' }, { table: 'disputes_deductions', fk: 'invoice_number', title: 'Disputes' }] } },
          { title: 'Customer payments', table: 'customer_payments' },
          { title: 'Disputes & deductions', table: 'disputes_deductions' },
          { title: 'Credit holds', table: 'credit_holds' },
        ] },
      { id: 'returns', group: 'Finance', label: 'Returns & Service', icon: '↩',
        tables: [
          { title: 'RMAs', table: 'rmas', detail: { key: 'rma_number', related: [{ table: 'warranty_claims', fk: 'rma_number', title: 'Warranty claim' }] } },
          { title: 'Warranty claims', table: 'warranty_claims' },
          { title: 'Field service orders', table: 'field_service_orders' },
        ] },
      { id: 'eng', group: 'Finance', label: 'Engineering & Compliance', icon: '§',
        tables: [
          { title: 'Engineering change orders', table: 'engineering_change_orders' },
          { title: 'Item revisions', table: 'item_revisions' },
          { title: 'Trade compliance (HTS / ECCN)', table: 'trade_compliance' },
          { title: 'Customs entries', table: 'customs_entries' },
        ] },
      { id: 'gl', group: 'Finance', label: 'Finance & GL', icon: '≡',
        kpis: [
          { label: 'GL entries', value: () => fmtInt(T.general_ledger.total) },
          { label: 'Software spend / yr', value: () => money(sum(rows('software_subscriptions'), 'annual_cost')) },
          { label: 'Indirect AP', value: () => money(sum(rows('ap_vendor_invoices_indirect'), 'amount')) },
        ],
        tables: [
          { title: 'Budget vs actual', table: 'budget_vs_actual' },
          { title: 'General ledger', table: 'general_ledger' },
          { title: 'Cost variances', table: 'cost_variances' },
          { title: 'Inventory valuation', table: 'inventory_valuation' },
          { title: 'Indirect vendor invoices', table: 'ap_vendor_invoices_indirect' },
          { title: 'Corporate vendors', table: 'corporate_vendors' },
          { title: 'Software subscriptions', table: 'software_subscriptions' },
          { title: 'Chart of accounts', table: 'chart_of_accounts' },
          { title: 'Operating bank statement', table: 'bank_statement_operating' },
        ] },
      { id: 'hr', group: 'People', label: 'HR & EHS', icon: '☺',
        kpis: [
          { label: 'Headcount', value: () => fmtInt(count(rows('employees'), (e) => e.status === 'Active')) },
          { label: 'OSHA recordables', value: () => fmtInt(count(rows('ehs_incidents'), (i) => i.osha_300_logged === 'Y')) },
          { label: 'Expiring certs', value: () => fmtInt(count(rows('training_certifications'), (t) => t.status !== 'Current')) },
        ],
        tables: [
          { title: 'Employees', table: 'employees', detail: { key: 'employee_id', titleCol: 'full_name', related: [{ table: 'payroll_register', fk: 'employee_id', title: 'Payroll' }, { table: 'pto_balances', fk: 'employee_id', title: 'PTO' }, { table: 'training_certifications', fk: 'employee_id', title: 'Training' }] } },
          { title: 'EHS incidents', table: 'ehs_incidents' },
          { title: 'Safety observations', table: 'safety_observations' },
          { title: 'Training & certifications', table: 'training_certifications' },
          { title: 'Payroll register', table: 'payroll_register' },
        ] },
      { id: 'docs', group: 'Records', label: 'Documents & Emails', icon: '✉', docs: true, tables: [{ title: 'Document index', table: 'document_index' }] },
      { id: 'explorer', group: 'Records', label: 'All Data Files', icon: '▤', explorer: true },
    ],
  });
})();
